# Generated by Django 4.0.1 on 2022-01-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yasherka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='название')),
                ('image', models.TextField(max_length=5000, verbose_name='URL изоображения')),
                ('date', models.CharField(max_length=200, verbose_name='Дата')),
            ],
        ),
    ]
