# Generated by Django 4.0.1 on 2022-02-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_pashalkaone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pashalkatwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=5000, verbose_name='Текст')),
            ],
        ),
    ]
